### ISSUE TITLE
Cannot use vue3-typed-js in vue3 template from vite

### ISSUE THREAD

**Issue by 0ojixueseno0** [Verdicts-ye/vue3-typed-js#1]
When I import this plugin like Readme
The console throw a error like:
`The requested module '/node_modules/typed.js/lib/typed.js?v=7c9b72e2' does not provide an export named 'default'`

导入包时控制台报错
用的是vite和vue3

**Comment by Verdicts-ye** [comment]
抱歉，我自己都好久没用这个玩意了。以前无聊试着打包一个npm包玩玩的。我自己安装引用没出现这个问题，主要麻烦在安装typed.js的时候容易出问题0.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Verdicts-ye/vue3-typed-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月30日(星期四) 晚上7:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Verdicts-ye/vue3-typed-js] Cannot use vue3-typed-js in vue3 template from vite (Issue #1)





 
When I import this plugin like Readme
 The console throw a error like:
 The requested module '/node_modules/typed.js/lib/typed.js?v=7c9b72e2' does not provide an export named 'default'
 
导入包时控制台报错
 用的是vite和vue3

**Comment by zzzzz167** [comment]
同样的问题,请问一下怎么解决捏

**Comment by 0ojixueseno0** [comment]
> 

我是换了个插件实现这个效果 https://github.com/pengqiangsheng/easy-typer-js 

在我的实例里面有关这个的代码是这样的：
```vue.js
<script setup>
import EasyTyper from 'easy-typer-js'
import { ref, onMounted } from "vue";
const obj = ref({
  output: '',
  isEnd: false,
  speed: 40,
  singleBack: false,
  sleep: 1000,
  type: 'rollback',
  backSpeed: 40,
  sentencePause: false
})
const noticeMsgs = [
  "1234567890",
  "0987654321",
  "asdfghjkl",
  "lkjhgfdsda"
]
const noticeMsg = function() {
  const typer = new EasyTyper(obj.value, noticeMsgs[noticed], noticeMsg)
  noticed = (noticed === noticeMsgs.length - 1 ) ? 0 : noticed + 1
  obj.value.speed = 1300 / noticeMsgs[noticed].length
  obj.value.backSpeed = 1000 / obj.value.speed
}
onMounted(() => {
  setTimeout(() => {
    // 一些无关的代码 省略...
    setTimeout(() => {
        noticeMsg()
    }, 500);
  }, 500);
});
</script>

<template>
<p>{{ obj.output }}&nbsp;<span class="
              animate__animated
              animate__flash
              animate__infinite">|</span></p>
</template>
```
这三个 animate__xxx 的 class 是来源于 animate.css 的 css 动画，用于制作光标效果
（毕竟是从写好的屎山里面挑着复制出来的 不一定能用 详情参照那个仓库的内容，虽然那个我也踩了半天坑）
